// ============================================================
// supabase-store.js — Baileys auth state
// Only the identity key (creds.json) is persisted to Supabase.
// All other state (pre-keys, sessions, sender-keys) is ephemeral —
// regenerated fresh on every restart. This eliminates Invalid PreKey ID
// errors caused by stale pre-key bundles in Supabase diverging from
// what WhatsApp servers have registered.
// ============================================================

const { useMultiFileAuthState } = require('@whiskeysockets/baileys');
const fs   = require('fs/promises');
const path = require('path');

const BUCKET   = 'whatsapp-sessions';
const AUTH_DIR = '/tmp/baileys-auth';
const CREDS_FILE = 'creds.json';

const delay = (ms) => new Promise(r => setTimeout(r, ms));

async function useSupabaseAuthState(supabase) {
  await fs.mkdir(AUTH_DIR, { recursive: true });

  // ── Restore ONLY the identity key from Supabase ─────────────
  // Pre-keys, sessions, sender-keys are intentionally NOT restored.
  // They are re-generated by Baileys on every restart, which keeps
  // them in sync with WhatsApp servers and prevents crypto mismatches.
  let identityRestored = false;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const { data, error } = await supabase.storage.from(BUCKET).download(CREDS_FILE);
      if (data && !error) {
        await fs.writeFile(path.join(AUTH_DIR, CREDS_FILE), await data.text(), 'utf-8');
        console.log('[supabase-auth] ✅ Identity restored — same device, no QR needed');
        identityRestored = true;
        break;
      }
      const notFound = error?.statusCode === 404 || error?.message?.toLowerCase().includes('not found');
      if (notFound) {
        console.log('[supabase-auth] First run — new identity will be created, scan QR');
        break;
      }
      console.warn(`[supabase-auth] Identity download attempt ${attempt}:`, error?.message);
    } catch (e) {
      console.warn(`[supabase-auth] Identity download attempt ${attempt} exception:`, e.message);
    }
    if (attempt < 3) await delay(800 * attempt);
  }

  if (!identityRestored) {
    console.log('[supabase-auth] Starting with fresh identity');
  }

  // ── Use official Baileys auth state ──────────────────────────
  const { state, saveCreds: _saveCreds } = await useMultiFileAuthState(AUTH_DIR);

  // ── Persist ONLY creds.json to Supabase ──────────────────────
  const saveCreds = async () => {
    await _saveCreds(); // write creds.json to local FS
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        const content = await fs.readFile(path.join(AUTH_DIR, CREDS_FILE), 'utf-8');
        const { error } = await supabase.storage.from(BUCKET)
          .upload(CREDS_FILE, Buffer.from(content), { upsert: true, contentType: 'application/json' });
        if (!error) {
          console.log('[supabase-auth] Identity saved to Supabase');
          return;
        }
        console.error(`[supabase-auth] Identity save attempt ${attempt}:`, error.message);
      } catch (e) {
        console.error(`[supabase-auth] Identity save attempt ${attempt} exception:`, e.message);
      }
      if (attempt < 3) await delay(800 * attempt);
    }
    console.error('[supabase-auth] ❌ Could not save identity — will need QR on next cold start');
  };

  return { state, saveCreds };
}

module.exports = { useSupabaseAuthState };
